### ISSUE TITLE
Rabbit 3.6.6 - Experimental ?

### ISSUE THREAD

**Issue by henry-hz** [tonyg/rabbithub#6]
Hi @tonyg , thanks for sharing rabbithub, please, let me ask some questions, 

is rabbithub still experimental ? Should work with Rabbit 3.6.6 ? is it compatible with [resthooks]( http://resthooks.org/) ?

**Comment by tonyg** [comment]
Hi @henry-hz -- From my perspective, rabbithub is still experimental, though I have not worked on it for many years now. Please do check the current maintainer's fork, https://github.com/brc859844/rabbithub, and also the fork of gfiehler https://github.com/gfiehler/rabbithub who seems to have been doing some interesting work on it. I don't know whether or not it will run with Rabbit 3.6.6. Regarding resthooks, I don't think it will be compatible, as it looks like resthooks was developed subsequent to PubSubHubBub, which is the foundation for rabbithub. However, adding resthooks support might be an interesting thing to try, and might not be too disruptive to the existing code.

**Comment by henry-hz** [comment]
Thanks @tonyg for the feedback. Yep, I will suggest resthooks for the fork maintainers :)
In fact, I just found that they updated to 3.6, and also created a cool web-admin UI plugin:
https://github.com/gfiehler/rabbithub_management

**Comment by brc859844** [comment]
Henry,

I've tested my current fork up to RabbitMQ 3.6.1. I'll try to find some time to try it with 3.6.6. And yes, Gregg  Fiehler has made some nice additions.

In terms of "experimental", I am certainly aware of some people using RabbitHub in fairly important production environments and encountering no problems.

**Comment by henry-hz** [comment]
amazing, thanks for the feedback @tonyg
