### ISSUE TITLE
Can't build the code for installation

### ISSUE THREAD

**Issue by paridhishr** [tonyg/rabbithub#7]
I am trying to install rabbithub plugin through the mentioned steps in the Readme file but I am stuck in the installation itself. At the step where 'make' is to be done after 'make deps', an error pops up saying -

src/rabbithub_pseudo_queue.erl:27: record amqqueue undefined
src/rabbithub_pseudo_queue.erl:26: Warning: variable 'Pid' is unused
src/rabbithub_pseudo_queue.erl:26: Warning: variable 'QueueName' is unused
src/rabbithub_pseudo_queue.erl:27: record amqqueue undefined
src/rabbithub_pseudo_queue.erl:26: Warning: variable 'Pid' is unused
src/rabbithub_pseudo_queue.erl:26: Warning: variable 'QueueName' is unused
ERROR: compile failed while processing /home/paridhi/rabbithub: rebar_abort
Makefile:40: recipe for target 'compile' failed
make: *** [compile] Error 1

I tried declaring the record amqqueue in the specified file but then same record seems to be undeclared in some other file. Any idea why this might be happening?

**Comment by tonyg** [comment]
Which version of Rabbit did you use? This codebase is really only of historical interest; you will have to use a version of Rabbit from about the same time as RabbitHub was written to make it work. I haven't tried to build or run the code in several years now. I believe @brc859844 has an active fork at https://github.com/brc859844/rabbithub - perhaps try that one.
